### ISSUE TITLE
On windows XP, on service stop randomly warning

### ISSUE THREAD

**Issue by cedseat** [mullvad/windows-service-rs#5] opened 2018-06-19 21:36 UTC
Hi,
When i test the ping_service on windows XP, randomly this warning is displayed : Windows could not stop the Ping service service on Local Computer. The service did not return an error. This could be an internal Windows error.
Thanks for your help.

Cédric

**Comment by pronebird** [comment] 2018-06-20 06:04
Hi,

Windows XP hit its end of life over 4 years ago but out of curiosity I'll pull the Windows XP VM and see why that happens. IIRC all APIs we use for windows services should be available on XP.

**Comment by pronebird** [comment] 2018-06-20 08:33
I poked around just for fun, but I couldn't even run the rust compiler nor rustup on my virtual machine. 

Rust support for Windows XP is [tier 3](https://forge.rust-lang.org/platform-support.html) meaning that it's pretty much not going to work.

Hence closing this issue. Update your OS, it's been 17 years.

**Closed by pronebird** 2018-06-20 08:33 UTC

**Comment by hcs64** [comment] 2018-06-26 20:49
I wasn't able to get a Rust binary running on XP to test this, but it reminded me of [a workaround in the Mozilla maintenance service](https://searchfox.org/mozilla-central/rev/14cb8f1c238735ba1abe18ad44e39808983c2572/toolkit/components/maintenanceservice/maintenanceservice.cpp#203-214):

 > There is an issue on XP SP2 and below where the service can hang
 > in a stop pending state even though the SCM is notified of a stopped
 > state.  Control *should* be returned to StartServiceCtrlDispatcher from the
 > call to SetServiceStatus on a stopped state in the wmain thread.
 > Sometimes this is not the case though. This thread will terminate the process
 > if it has been 5 seconds after all work is done and the process is still not
 > terminated.  This thread is only started once a stopped state was sent to the
 > SCM. The stop pending hang can be reproduced intermittently even if you set
 > a stopped state dirctly and never set a stop pending state.  It is safe to
 > forcefully terminate the process ourselves since all work is done once we
 > start this thread.

But if you're running XP SP3 then perhaps this particular issue has already been fixed.
